module.exports = {
	'Milk': {rate: 40},
	'Cold Brew': {rate: 40},
	'Warm Coffee': {rate: 40},
	'Half and Half': {rate: 40},
	'Sprite': {rate: 40},
	'Grenadine': {rate: 40},
	'Lemonade': {rate: 40},
	'Iced Tea': {rate: 40},
	'Hot Tea': {rate: 40},
	'Pineapple': {rate: 40},
	'Lime Juice': {rate: 40},
	'Apple Juice': {rate: 40},
	'Lemon Juice': {rate: 40},
	'Simple Syrup': {rate: 40},
	'Tonic Water': {rate: 40},
	'Orange Juice': {rate: 40},
	'Sparkling Water': {rate: 40},
	'Cranberry Juice': {rate: 40},
	'Grapefruit Juice': {rate: 40},
	'Peach Nectar': {rate: 40},
	'Blue Gatorade': {rate: 40},
	'Coke': {rate: 40},
	'Ginger Ale': {rate: 40},
	'White Grape Juice': {rate: 40},
	'Ginger Beer': {rate: 40},
	'Coconut Water': {rate: 40}
};